### ISSUE TITLE
Bug, Gate Can't Be Opened

### ISSUE THREAD

**Issue by ardissaps** [MIUNO/NiceMod#3]
![image](https://user-images.githubusercontent.com/82106625/174698973-efa36249-b3c1-4a81-a5a4-b5efa5971a84.png)

**Comment by MIUNO** [comment]
This is a decorative block
If someone can give it functionality, I will be very grateful

**Comment by ardissaps** [comment]
> This is a decorative block If someone can give it functionality, I will be very grateful

It is possible with Create Mod, put slime glue on rope pulley and other necessity. and some lever red stone thing, (similiar with piston).
