### ISSUE TITLE
Villager Pathing Fail through NiceMod Blocks

### ISSUE THREAD

**Issue by Dragonfly-Totem** [MIUNO/NiceMod#6]
NiceMod 1.1
Fabric 0.14.8
Minecraft 1.19

Using the column and fence post blocks appears to interact with villager pathing in a negative way; Specifically, villagers try to path through the blocks as though they are not there.  Changing the blocks out for something else -- For example, replacing posts with vanilla fence posts -- has the villagers path around the fence posts as expected behavior.

It's not a dealbreaker on the mod, by any means, but it's definitely occasionally frustrating to see five or six villagers just bouncing headfirst into a post or column block over and over and over again, because they seem to think they can path straight through it.

**Comment by MIUNO** [comment]
Not only villagers, but in general any mobs with intelligence.
I am aware of the problem and hope that I will be able to solve it soon.

**Comment by Psychodeus** [comment]
Solved in the new update, cheers.
