### ISSUE TITLE
Some blocks remove faces when they don't need too

### ISSUE THREAD

**Issue by netcore10** [MIUNO/NiceMod#7]
![image](https://user-images.githubusercontent.com/181536/200670973-42e331dd-8662-4755-850e-b5e11ad7e6b3.png)

**Comment by MIUNO** [comment]
Do you use an optifine?

**Comment by MIUNO** [comment]
Most likely the problem is in the shader

**Comment by netcore10** [comment]
oh damn. So there's no plan for compatability with iris?

**Comment by MIUNO** [comment]
The mod is compatible with Iris, for example Sildur's Vibrant Shaders works as it should

**Comment by netcore10** [comment]
i see, odd, maybe it's the shader type?
